import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { CustomerProvider } from "@/components/CustomerContext";
import { SelectionProvider } from "@/components/SelectionContext";
import { getCustomers } from "@/utils/customers";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  const customers = await getCustomers();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <CustomerProvider initialCustomers={customers}>
          <SelectionProvider>
            {children}
            {modal}
          </SelectionProvider>
        </CustomerProvider>
      </body>
    </html>
  );
}
